GET http://localhost:5000/api/authors

###
POST http://localhost:5000/api/authors
Content-Type: application/json

{
    "name" : "Test2"
}

###
GET http://localhost:5000/api/authors/68c93785a583ec13f99155b0

###
PUT http://localhost:5000/api/authors/68c9379ca583ec13f99155b3
Content-Type: application/json

{
    "name" : "Test3"
}

###
DELETE http://localhost:5000/api/authors/68c936e5a583ec13f99155ab