GET http://localhost:5000/api/genres

###
POST http://localhost:5000/api/genres
Content-Type: application/json

{
    "name" : "Test23"
}

###
GET http://localhost:5000/api/genres/68c96df5afa39d4856b03823

###
PUT http://localhost:5000/api/genres/68c96df5afa39d4856b03823
Content-Type: application/json

{
    "name" : "Test1"
}

###
DELETE http://localhost:5000/api/genres/68c969c4214f88ef83896d52